### ISSUE TITLE
Import / Export issue from Sifchain

### ISSUE THREAD

**Issue by Vyacheslav999** [Sifchain/Support-Tickets#242]
## Describe the bug

A Detailed description of the issue (what happened, token affected and token amount)
I threw about 19 Atom from the sifchain (sif13gqun5f87xdp74jqvx4qw6wql0wymuy7t8w6cc) to Kepler (cosmos13gqun5f87xdp74jqvx4qw6wql0wymuy7w6pvhn), the transaction hung at first for 20 minutes, and then completely disappeared - there is nothing in the mintscan or on Kepler or on the sifchain

## How to Reproduce

4. See error "..."

## Expected behaviour
Please write a clear and detailed description of what you expected to happen.

## TX Hashes
Please provide links to transaction hashes of the import / export issues you are facing

## Addresses
Please provide links to your addresses (**both** of Sifchain and external chain)
sif13gqun5f87xdp74jqvx4qw6wql0wymuy7t8w6cc
cosmos13gqun5f87xdp74jqvx4qw6wql0wymuy7w6pvhn

## Error logs
Please provide links to your addresses (both of Sifchain and external chain)

sif13gqun5f87xdp74jqvx4qw6wql0wymuy7t8w6cc
cosmos13gqun5f87xdp74jqvx4qw6wql0wymuy7w6pvhn

## Screenshots

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by Vyacheslav999** [comment]
Everything is in order, the amount returned back to Sifchain
Can you clarify what the bug might be related to?

**Comment by lufa23** [comment]
hey, happy to hear funds arrived!
This issue can be caused by delays with IBC packets.. 
When you import or export tokens across blockchains, a relayer needs to relay the message through an IBC channel. If for whatever reason the channel is experiencing delays, then the transaction is not correctly processed.

Sometimes if you see that your transaction is not getting processed, you can check the [ibc-status channel](https://discord.com/channels/769209144515100693/890703929178996797) on Discord, to see when the channel is fully functional again :)
