### ISSUE TITLE
ticket

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#303]
edited

**Comment by Kalabus** [comment]
I only received 7 day's worth of rewards, and not the 8 day's worth of rewards.  I have lots of screenshots I can share of reward counts at different intervals/days.  This spreadsheet shows the  last couple month's worth of my rewards, the Amount Claimed, the Rowans/Hour I received, and the Difference in Hourly from one week to the next.  You can see that they are climbing every week (with the exception of one week when we got a payout on Wednesday instead of Tuesday, so therefore lost a day of accumulation).  IF the rewards I received were for 7 days (the line highlighted in yellow) that would make sense, comparing with the increasing ratios before that (from compounding every week).  However, For 8 days accumulation (highlighted in pink), I am earning 302 less per hour than I was last week, which is AFTER I put in $103,000 USD.  Therefore, I lost out on a full day of accumulation, which would be about $14,000 USD. 
 
![image](https://user-images.githubusercontent.com/97975820/161873579-61278f85-a11e-44aa-8d19-438005fe05f1.png)

**Comment by emperorjm** [comment]
Hi @Kalabus. Based on our records you have earned more rewards this week than last week and previous weeks.

Previous Week
----------------

Expansion (2022-03-28 22:59:37.957 -0400): 613,569.185172487 ROWAN
Harvest (2022-03-29 00:45:27.275 -0400): 259,887.0386400959 ROWAN


Current
---------

Expansion (2022-04-05 05:07:26.221 -0400): 629,845.4195911499 ROWAN
Harvest (2022-03-29 00:45:27.275 -0400): 314,922.70979557495 ROWAN

**Comment by Kalabus** [comment]
Yes that is correct...your numbers are slightly off from what my screenshots show, but close enough.  And I should have increased rewards now because I put compounded in my previous week's rewards of $90,647.  The issue though is my rewards this week would be an acceptable rowan per hour IF we were only talking 7 days of rewards, but we should be getting 8 days worth of rewards, and my rowan per hour is therefore way less than my previous couple weeks of rewards.  How can that be when I have put in over $150k in rewards over the past two weeks?

On 3/28 I got rewards of 873461.21 (minus a few I had in there for swaps)
![image](https://user-images.githubusercontent.com/97975820/161883663-b72ca3b3-d184-4e91-b581-2566f111bc8d.png)

On 3/29 I added in around $90,374.88 in liquidity...from 3/22 until 3/29 was 5199.144167 Rowans gained per hour (873456.22/168 hours):
![image](https://user-images.githubusercontent.com/97975820/161883752-9e561a7b-7b0b-41c9-8ede-75fc216564a9.png)

This week's rewards in my Balance (I had a few in there for swaps)...944771.94 divided by 168 (24 hours * 7 days) is 5,623.6425 per day, which makes sense considering the $90k I added in there previously:
![image](https://user-images.githubusercontent.com/97975820/161884102-b887c00a-a9f5-4abb-b7c4-562434fd9b1c.png)

As stated though, 944771.94 divided by 192 (24 hours * 8 days) is only 4,920.6872 Rowan per hour, which is way less rewards than the past several weeks.  How can I be earning far less per hour after putting in $90k and the price of Rowan is pretty similar to what it was previously?

On 3/22, my Rewards from the previous week had come in, and was 819140.95 (minus a few I had in there for swaps):
![image](https://user-images.githubusercontent.com/97975820/161884633-46e596a4-8e78-4aa1-9ca2-941eed0bbd8f.png)

I then added in liquidity of around $76,611:
![image](https://user-images.githubusercontent.com/97975820/161884706-0c4d7dbc-7860-4d64-8fc4-38b4fe4999d9.png)

How can I be receiving far less rowan per hour this week than I did in previous weeks, when you consider we should be getting 8 day's worth of rewards?

I have a lot more screenshots and such that I can show you if necessary.  Thanks!

**Comment by Kalabus** [comment]
And taking this a step further, on 3/29 BEFORE you guys changed servers or whatever which reset the rewards counter, from 8:13am EST to 9:13am EST, I had gained 5534.8781 rewards for that hour, while Rowan was at 10.3 cents.  

![image](https://user-images.githubusercontent.com/97975820/161888848-7f6b5e11-8392-41d8-aeb3-ef1fa3cfea78.png)

How is it that after you guys give us 8 days of Rewards that I then earn 4,920.6872 Rowan per hour?

**Comment by emperorjm** [comment]
@Kalabus let me dig into this a bit more and get back to you.

**Comment by Kalabus** [comment]
Great @emperorjm!  Thanks so much!

**Comment by emperorjm** [comment]
Hi @Kalabus. Based on discussions with the team, the cutover to the new rewards implementation saw a change to the rewards calculation formula (see new formula here https://docs.sifchain.finance/using-the-website/web-ui-step-by-step/rewards#reward-calculations) as the old formula was over paying some accounts. The amounts distributed this week are correct and will be the benchmark going forward.

**Comment by Kalabus** [comment]
Thank you for discussing with the Team, but it still doesn't seem to add up for me.  And can you tell me if I was paid out for 7 days or 8?:

- from 3/22 until 3/29 I earned 5199.144167 Rowans gained per hour (873456.22/168 hours)
- after 3/29, after the rewards reset themselves, IF it was for 8 days, I only received 4,920.6872 Rowan per hour, which as you said is based on the new benchmark
- I am now making 5487.38 per hour, based on an average of the last 4 hours

![image](https://user-images.githubusercontent.com/97975820/162024344-68da7313-0efc-4ce1-978c-853a917eeecd.png)

Do you by chance have a spreadsheet you can share to assist with those calculations?  Thanks again!

**Comment by emperorjm** [comment]
As the price of rowan affects the rewards earned the amount earned from the 2nd to the 5th of June when ROWAN was over 11cents would be less than those earned in the last 4 fours where rowan is almost under 10 cents. You will not earn the same amount of tokens every hour if the ROWAN price continuously fluctuates. I will still forward your query to the Devs.

**Comment by Kalabus** [comment]
Thanks so much!  Do you by chance have a spreadsheet you can share to assist with those calculations? Thanks again!

**Comment by siffuku** [comment]
wow you made 6 mill rewards and are wasting dev time over pennies?? get real man, let devs focus on other issues, you make $600k in rewards lol
