### ISSUE TITLE
Asymmetric liquidity adds

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#362]
**Please write a detailed description of the issue.**
There is something seriously wrong with SIFchain. Before the move to PMTP I had 1.5 Eth, a week ago I converted ATOM to ETH and added another 0.5. I check my balances today: 0.938134 ETH not sure what happened?

**What is the name and amount of the token affected?**
ETH - went from > 2 ETH to 0.938134 over last 2ish weeks

**What is your Sifchain address?**
Not sure

**What is your address on the other chain?**
My KEPLR?

**What is the link to the transaction has you are having problem with?**
None, my ETH is in the pool, balance has gone down

**Are there any error logs you can share?**
That would be on your end

**Comment by lufa23** [comment]
hey let us get back to you on this

**Comment by lufa23** [comment]
From what i can see, you have made several **asymmetric** liquidity add transactions, like
https://www.mintscan.io/sifchain/txs/7021627AC4A88C6665657E4C9591212334CBEE76A7EDB54DA9BBDC40934E427A
https://www.mintscan.io/sifchain/txs/6C1D5B3039FEAEAE789563D4CEAC99B1F79C03BD9DAFAED7A413DF8FEEB99498

The only symmetric liquidity add that i can see in the eth pool, is this one:
https://www.mintscan.io/sifchain/txs/A596C4D2B24FCE79B3F593A868D4241EF3851AB5DEB04C5693B0C71D4F2D245C

When it comes to asymmetric adds, you may lose your principal rapidly to arbitrageurs depending on:
- the depth of the pool
- How much that pool is balanced / unbalanced
- the size of your asymmetric addition

Are you familiar with the implications of asymmetric liquidity addition?
If not, we highly suggest you to have a look [at our docs](https://docs.sifchain.finance/using-the-website/pool#asymmetrical-liquidity-additions)

Also, i can see that in the last few weeks you may have witnessed some Impermanent Loss due to price fluctuations. It seems that alone would account on the ROWAN - ETH pool for around 22% of your principal value
